# Generated by Django 4.2 on 2024-10-23 21:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Family',
            fields=[
                ('lastname', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('number_of_members', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Families',
            },
        ),
        migrations.CreateModel(
            name='House',
            fields=[
                ('house_address', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('family', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='one_to_one.family')),
            ],
        ),
    ]
