# Generated by Django 4.2 on 2024-10-23 21:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('max_student_number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('name', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('skill_level', models.CharField(choices=[('bad', 'Bad'), ('ok', 'Ok'), ('good', 'Good')], default='ok', max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('avg_grade', models.FloatField(max_length=4)),
                ('classes', models.ManyToManyField(to='many_to_many.class')),
            ],
        ),
        migrations.AddField(
            model_name='class',
            name='professor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='many_to_many.professor'),
        ),
    ]
